project:
  type: website
  output-dir: docs

website:
  title: "Waterway Ecosystem Research Group"
  subtitle: "Advancing the urban water industry using real-time control technologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

